apiVersion: infra.k8smgmt.io/v3
kind: AddonOverride
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: ingress-nginx
  project: defaultproject
spec:
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: surya-terraform-cluster01
  resource:
    selector:
      name: ingress-nginx
    type: Addon
  type: Helm
  valuesPath:
    name: file://ingress-nginx/ingress-nginx.yaml
