apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: factset-constraint-template
  project: surya
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/factset-constraint-template/rafay-gatekeeper-allowedrepos-constraint-template.yaml
    options: {}
    type: Yaml
