apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  name: factset-constraints
  project: surya
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/factset-constraints/rafay-gatekeeper-allowedrepos-constraint.yaml
    options: {}
    type: Yaml
  published: true
  templateName: factset-constraint-template
  version: v1
