apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  name: factset-constraints-ratio
  project: surya
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/factset-constraints-ratio/rafay-request-limit-ratio-constraint.yaml
    options: {}
    type: Yaml
  published: true
  templateName: factset-constraint-template-ratio
  version: v1
