apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: nodepool-addon
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/nodepool-addon/nodepool.yaml
    type: Yaml
  namespace: karpenter
  sharing: {}
  version: v1
