apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: kube-system
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: surya-takeda-cluster08
    - key: rafay.dev/clusterName
      value: mysql-db-cluster
  resourceQuotas: {}
