apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: prom2teams
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: surya-softwareag-cluster13
  resourceQuotas: {}
