global:
  resolve_timeout: 5m
  slack_api_url: https://hooks.slack.com/services/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
inhibit_rules:
- equal:
  - alertname
  - rc_edgeid
  - service
  source_match:
    severity: critical
  target_match:
    severity: warning
receivers:
- name: default-receiver
- name: rafay-webhook
  webhook_configs:
  - http_config:
      tls_config:
        ca_file: /etc/config/certs/ca.crt
        cert_file: /etc/config/certs/client.crt
        insecure_skip_verify: true
        key_file: /etc/config/certs/client.key
        server_name: '{{{ .V2EventFrameworkFQDN }}}'
    url: https://{{{ .V2EventFrameworkFQDN }}}/event/v1/alert/raise
- name: myalerts
  slack_configs:
  - channel: '#alerts-demo'
    send_resolved: true
    title_link: nil
route:
  group_interval: 5m
  group_wait: 10s
  receiver: rafay-webhook
  repeat_interval: 3h
  routes:
  - continue: true
    match_re:
      severity: .*
    receiver: rafay-webhook
  - match_re:
      severity: .*
    receiver: myalerts
