apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: prometheus
    chart: prometheus-11.0.2
    component: alertmanager
    heritage: Helm
    release: rafay-prometheus
  name: rafay-prometheus-alertmanager
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: alertmanager
      release: rafay-prometheus
  serviceName: rafay-prometheus-alertmanager-headless
  template:
    metadata:
      labels:
        app: prometheus
        chart: prometheus-11.0.2
        component: alertmanager
        heritage: Helm
        release: rafay-prometheus
    spec:
      containers:
      - args:
        - --config.file=/etc/config/alertmanager.yml
        - --storage.path=/data
        - --cluster.advertise-address=$(POD_IP):6783
        - --web.external-url=http://localhost:9093
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: registry.rafay-edge.net/rafay/alertmanager:v0.24.0
        imagePullPolicy: IfNotPresent
        name: prometheus-alertmanager
        ports:
        - containerPort: 9093
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9093
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /etc/config/certs
          name: event-framework-certs
        - mountPath: /data
          name: storage-volume
          subPath: ""
      - args:
        - --volume-dir=/etc/config
        - --webhook-url=http://127.0.0.1:9093/-/reload
        image: registry.rafay-edge.net/rafay/prom-configmap-reload:v0.8.0
        imagePullPolicy: IfNotPresent
        name: prometheus-alertmanager-configmap-reload
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: rafay-prometheus-alertmanager
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: rafay-prometheus-alertmanager
      - name: event-framework-certs
        secret:
          defaultMode: 420
          secretName: rafay-event-framework-certs-am
      - emptyDir: {}
        name: storage-volume
