apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: factset-opa-test01
  project: defaultproject
spec:
  blueprintConfig:
    name: default
    version: Latest
  cloudCredentials: surya-eks-cloud-credentials
  config:
    addons:
    - name: coredns
      version: v1.10.1-eksbuild.4
    - name: vpc-cni
      version: v1.15.1-eksbuild.1
    - name: kube-proxy
      version: v1.28.2-eksbuild.2
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceTypes:
      - t3.medium
      maxSize: 2
      minSize: 2
      name: ng-07015e6c
      version: "1.28"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: factset-opa-test01
      region: us-west-2
      tags:
        email: suryakant@rafay.co
        env: automation
      version: "1.28"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
