apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: ss45
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: surya-aks-cc01
  config:
    kind: aksClusterConfig
    metadata:
      name: ss45
    spec:
      managedCluster:
        apiVersion: "2022-07-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: true
          dnsPrefix: ss45-dns
          enableRBAC: true
          kubernetesVersion: 1.29.4
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
          powerState:
            code: Running
        sku:
          name: Basic
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2022-07-01"
        location: centralindia
        name: primary
        properties:
          count: 1
          enableAutoScaling: true
          maxCount: 1
          maxPods: 110
          minCount: 1
          mode: System
          orchestratorVersion: 1.29.4
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_DS2_v2
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: Surya-Resource-Group
  type: aks
