apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: opa-pipeline01
  project: defaultproject
spec:
  stages:
  - config:
      destinationRepo: {}
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        path:
          name: /turnkey-opa
        repository: op-repo01
        revision: master
      systemToGitSync: true
    name: opa-stage
    type: SystemSync
