apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: op-repo01
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAZ1RRZ4oLzCoEkGdPMySEzfPw0lP75booraeDIcQlyb7rVCx32d4h9VyVkunPm5hg65YxjaO9XbclCsV6/eyN9kB/S3aW5c1aUK9/vlYkaDQ2fFR8oWFi9yG3or+lcBWSnUzTssa3qkVlG5jGcUM9M3H1gNQfhnM6gQGDIBUOBmdk1CfpWkl/EIms9DXqVMZQPo4i31QCCWOH9IbPK+8Td7fng3l2QeCfVyn2bDc5/TbYRXOqCotCX+9b8Pc1Kr3WIpEbW/gzPJWEIPNPPrqcyECJ6cscVZRWDq2oinMPhQGyrOFcWeZ8CxmTYI1ULBal/fowvJ0gMdRZ9Oi5haxWGW0JJd1+fIdaIMoiRZsF6asLqiUcfoldFA+hw3/fgoYnCRa8WGBpJCDtrtikUZ7qQ7UM4VeFP7Vg=
  template:
    metadata:
      creationTimestamp: null
      name: op-repo01
      namespace: default

