apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: suryabp
  project: surya
spec:
  base:
    name: default
    version: 2.6.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
