apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: default-bitnami
  project: defaultproject
spec:
  endpoint: https://charts.bitnami.com/bitnami
  options: {}
  type: Helm
status:
  projects:
  - projectId: 3mx0o7m
    repositoryId: mx4l60k
