apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx-workload
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: default-bitnami
      chartName: nginx-ingress-controller
      chartVersion: 11.1.0
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: fidelity
  placement:
    selector: rafay.dev/clusterName=mks-test-cluster01
  version: nginx-workload-v1-202404161336110000
