apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: fidelity-bp
  project: defaultproject
spec:
  base:
    name: default-upstream
    version: 2.5.0
  customAddons:
  - name: nginx-fidelity
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    enableRookCeph: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Managed
  type: custom
  version: v4
