apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: mysql-blueprint1
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.4.0
  customAddons:
  - name: mysql-service
    version: v1
  - name: mysql-pvc
    version: v1
  - name: mysql-deployment
    version: v1
  - name: developer-sa
    version: v1
  - name: developer-role
    version: v1
  - name: developer-test-pod
    version: v1
  driftWebhook:
    enabled: true
  type: custom
  version: v1
