apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: pgadmin-blueprint
  project: defaultproject
spec:
  base:
    name: minimal
    version: 2.4.0
  customAddons:
  - name: pgadmin-service
    version: v1
  - name: pgadmin-deployment
    version: v1
  driftWebhook:
    enabled: true
  type: custom
  version: v1
