apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: pvc-blueprint
  project: defaultproject
spec:
  base:
    name: default
    version: 2.4.0
  customAddons:
  - name: mysql-pvc
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v2
